name: evaluate

on:
  workflow_dispatch:
  schedule:
    # veče, po UTC
    - cron: "45 20 * * *"

jobs:
  eval:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 1) download jutarnji artifact
      - name: Download morning pages artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: tmp_art

      # 2) prebaci u public/
      - name: Restore public from artifact
        run: |
          mkdir -p public
          cp -r tmp_art/* public/ || true
          ls -R public || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install httpx

      - name: Run evaluation
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
          API_FOOTBALL_URL: ${{ secrets.API_FOOTBALL_URL }}
        run: |
          python evaluate_ticket.py
          cat public/evaluation.json

      # 3) upload novi artifact za pages
      - name: Upload evaluated pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      # 4) deploy
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
